python mcm/experiments_mcm.py --data atomic --model use_1510_1699
python mcm/experiments_mcm.py --data atomic --model use_1700_1799
python mcm/experiments_mcm.py --data atomic --model use_1800_1899
python mcm/experiments_mcm.py --data atomic --model use_1800_1809
python mcm/experiments_mcm.py --data atomic --model use_1810_1819
python mcm/experiments_mcm.py --data atomic --model use_1820_1829
python mcm/experiments_mcm.py --data atomic --model use_1830_1839
python mcm/experiments_mcm.py --data atomic --model use_1840_1849
python mcm/experiments_mcm.py --data atomic --model use_1850_1859
python mcm/experiments_mcm.py --data atomic --model use_1860_1869
python mcm/experiments_mcm.py --data atomic --model use_1870_1879
python mcm/experiments_mcm.py --data atomic --model use_1880_1889
python mcm/experiments_mcm.py --data atomic --model use_1890_1899
python mcm/experiments_mcm.py --data atomic --model use_rcv1
python mcm/experiments_mcm.py --data atomic --model use_trc2
python mcm/experiments_mcm.py --data atomic --model use_1987
python mcm/experiments_mcm.py --data atomic --model use_rc
python mcm/experiments_mcm.py --data atomic --model use_news
python mcm/experiments_mcm.py --data atomic --model use_hub